/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package forme;

import domen.Mesto;
import domen.Odeljenje;
import domen.Ucenik;
import java.awt.Frame;
import java.util.ArrayList;
import logika.KontrolerKlijent;
import modeli.ModelTabeleOdeljenje;
import modeli.NoviModel;

/**
 *
 * @author HP ProBook 650 G2
 */
public class OdeljenjaKonkretnogMesta extends javax.swing.JDialog {
    Mesto mesto;
    /**
     * Creates new form OdeljenjaKonkretnogMesta
     */
    public OdeljenjaKonkretnogMesta(Frame parent, boolean modal, Mesto mesto) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(parent);
       tblOdeljenja.setModel(new ModelTabeleOdeljenje(mesto));
       //popuniOdeljenja();
        txtMesto.setText(mesto.toString());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblOdeljenja = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        txtMesto = new javax.swing.JLabel();
        btnZatvori = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tblOdeljenja.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblOdeljenja);

        jLabel1.setText("Odeljenja za mesto:");

        txtMesto.setFont(new java.awt.Font("Viner Hand ITC", 0, 12)); // NOI18N
        txtMesto.setText("Mesto");

        btnZatvori.setText("Zatvori");
        btnZatvori.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnZatvoriActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(txtMesto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnZatvori)))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtMesto)
                    .addComponent(btnZatvori))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnZatvoriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnZatvoriActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnZatvoriActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnZatvori;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblOdeljenja;
    private javax.swing.JLabel txtMesto;
    // End of variables declaration//GEN-END:variables

    /*private void popuniOdeljenja() {
        ArrayList<Ucenik> ucenici = new ArrayList<>();
        ArrayList<Odeljenje> odeljenja = new ArrayList<>();
        ArrayList<Odeljenje> novaOdeljenja = new ArrayList<>();
        try {
            odeljenja = KontrolerKlijent.getInstance().vratiOdeljenja();
            for (Odeljenje odeljenje : odeljenja) {
                 ucenici = KontrolerKlijent.getInstance().vratiUcenike(odeljenje);
                if(ucenici.get(0).getMesto().getMestoID() == mesto.getMestoID()){
                    novaOdeljenja.add(odeljenje);
                }
                
            }
            
            
            
        } catch (Exception ex) {
            
        }
    }    */  
}
